FROM mcr.microsoft.com/playwright:v1.63.0-jammy

ENV PNPM_HOME=/pnpm
ENV PATH=$PNPM_HOME:$PATH
ENV CI=true

RUN corepack enable

WORKDIR /app

COPY . .

RUN pnpm install --frozen-lockfile
RUN pnpm --filter @website-auditor/worker... build

CMD ["pnpm", "--filter", "@website-auditor/worker", "start"]
